name: Download and Unpack NuGet Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-and-unpack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install NuGet
      run: |
        sudo apt-get update
        sudo apt-get install -y nuget
        

    - name: Download WebView2 SDK
      run: nuget install Microsoft.Web.WebView2 -Version 1.0.1264.42 -OutputDirectory ./packages

    - name: Download WIL
      run: nuget install Microsoft.Windows.ImplementationLibrary -Version 1.0.210803.1 -OutputDirectory ./packages

    - name: Unpack WebView2 SDK
      run: unzip ./packages/Microsoft.Web.WebView2.1.0.1264.42/Microsoft.Web.WebView2.1.0.1264.42.nupkg -d ./packages/WebView2

    - name: Unpack WIL
      run: unzip ./packages/Microsoft.Windows.ImplementationLibrary.1.0.210803.1/Microsoft.Windows.ImplementationLibrary.1.0.210803.1.nupkg -d ./packages/WIL

    - name: Upload Release artifact (x64)
      uses: actions/upload-artifact@v4
      with:
        name: webview2
        path: packages
        
  create-release:
    runs-on: ubuntu-latest
    needs: download-and-unpack
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "RELEASE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Install GitHub CLI
        uses: sersoft-gmbh/setup-gh-cli-action@v2

      - name: Delete existing release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release delete $RELEASE_DATE --yes || true

      - name: Create new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $RELEASE_DATE -t "Release $RELEASE_DATE" -n "Automated release for $RELEASE_DATE"


      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Compress Artifacts
        run: |
          cd ./packages
          zip -r ../packages.zip ./*
 

      - name: Generate MD5 Checksums
        run: |
          > ./artifacts/filelist.txt  # 清空或创建 filelist.txt 文件
          for file in ./artifacts/*.zip; do
            # Calculate MD5 checksum
            md5sum=$(md5sum "$file" | awk '{ print $1 }')
            
            # Write to filelist.txt
            echo "$(basename "$file") | ${md5sum}" >> ./artifacts/filelist.txt
          done
          
      - name: Upload Artifacts to Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./artifacts
          gh release upload $RELEASE_DATE ./packages.zip
          gh release upload $RELEASE_DATE ./filelist.txt
